/**
 * Security validators for cluster / K8s configuration files.
 *
 * These validators are intentionally hard-coded (not generated by LLM) to
 * ensure that AI-generated YAML or configuration never bypasses critical
 * safety checks.
 */

/** Characters / patterns that are never allowed in YAML values. */
const DANGEROUS_PATTERNS = [
  /\$\(.*\)/,          // command substitution $(...)
  /`[^`]+`/,           // backtick command substitution
  /;\s*(rm|dd|mkfs)\b/,// chained destructive commands
  />\s*\/dev\/sd/,     // overwriting block devices
  /\|\s*bash\b/,       // piping to bash
  /\|\s*sh\b/,         // piping to sh
];

/**
 * Check whether a YAML string is safe for submission to the cluster.
 * Returns an object with `safe: boolean` and an optional `reason` string.
 */
export function validateYamlSafety(yaml: string): {
  safe: boolean;
  reason?: string;
} {
  // 1. Size guard
  if (yaml.length > 100_000) {
    return { safe: false, reason: "YAML exceeds 100 KB size limit." };
  }

  // 2. Reject truly dangerous patterns in values
  for (const pat of DANGEROUS_PATTERNS) {
    if (pat.test(yaml)) {
      return {
        safe: false,
        reason: `YAML contains a dangerous pattern: ${pat.source}`,
      };
    }
  }

  // 3. Require the apiVersion/kind header to look like a K8s manifest
  if (!/^apiVersion:\s*\S+/m.test(yaml)) {
    return {
      safe: false,
      reason: "YAML does not contain a valid apiVersion field.",
    };
  }
  if (!/^kind:\s*\S+/m.test(yaml)) {
    return {
      safe: false,
      reason: "YAML does not contain a valid kind field.",
    };
  }

  // 4. Disallow privileged security context
  if (/privileged:\s*true/i.test(yaml)) {
    return {
      safe: false,
      reason: "YAML sets privileged: true, which is not allowed.",
    };
  }

  // 5. Disallow hostNetwork / hostPID / hostIPC
  if (/hostNetwork:\s*true/i.test(yaml)) {
    return { safe: false, reason: "hostNetwork: true is not allowed." };
  }
  if (/hostPID:\s*true/i.test(yaml)) {
    return { safe: false, reason: "hostPID: true is not allowed." };
  }
  if (/hostIPC:\s*true/i.test(yaml)) {
    return { safe: false, reason: "hostIPC: true is not allowed." };
  }

  return { safe: true };
}

/**
 * Validate a K8s namespace name (DNS label).
 */
export function isValidNamespace(ns: string): boolean {
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(ns) && ns.length <= 63;
}

/**
 * Validate a job name (DNS label).
 */
export function isValidJobName(name: string): boolean {
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(name) && name.length <= 63;
}
